// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: JobResult.proto
// Protobuf Java Version: 4.29.1

package org.yx.hoststack.protocol.ws.server;

public final class JobResult {
  private JobResult() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      JobResult.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TargetResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.yx.hoststack.protocol.ws.server.TargetResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string jobDetailId = 1;</code>
     * @return The jobDetailId.
     */
    java.lang.String getJobDetailId();
    /**
     * <code>string jobDetailId = 1;</code>
     * @return The bytes for jobDetailId.
     */
    com.google.protobuf.ByteString
        getJobDetailIdBytes();

    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>uint32 code = 3;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>uint32 progress = 5;</code>
     * @return The progress.
     */
    int getProgress();

    /**
     * <code>string output = 6;</code>
     * @return The output.
     */
    java.lang.String getOutput();
    /**
     * <code>string output = 6;</code>
     * @return The bytes for output.
     */
    com.google.protobuf.ByteString
        getOutputBytes();
  }
  /**
   * Protobuf type {@code org.yx.hoststack.protocol.ws.server.TargetResult}
   */
  public static final class TargetResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.yx.hoststack.protocol.ws.server.TargetResult)
      TargetResultOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        TargetResult.class.getName());
    }
    // Use TargetResult.newBuilder() to construct.
    private TargetResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TargetResult() {
      jobDetailId_ = "";
      status_ = "";
      msg_ = "";
      output_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.class, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder.class);
    }

    public static final int JOBDETAILID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jobDetailId_ = "";
    /**
     * <code>string jobDetailId = 1;</code>
     * @return The jobDetailId.
     */
    @java.lang.Override
    public java.lang.String getJobDetailId() {
      java.lang.Object ref = jobDetailId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobDetailId_ = s;
        return s;
      }
    }
    /**
     * <code>string jobDetailId = 1;</code>
     * @return The bytes for jobDetailId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJobDetailIdBytes() {
      java.lang.Object ref = jobDetailId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jobDetailId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_ = 0;
    /**
     * <code>uint32 code = 3;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object msg_ = "";
    /**
     * <code>string msg = 4;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 4;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROGRESS_FIELD_NUMBER = 5;
    private int progress_ = 0;
    /**
     * <code>uint32 progress = 5;</code>
     * @return The progress.
     */
    @java.lang.Override
    public int getProgress() {
      return progress_;
    }

    public static final int OUTPUT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object output_ = "";
    /**
     * <code>string output = 6;</code>
     * @return The output.
     */
    @java.lang.Override
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <code>string output = 6;</code>
     * @return The bytes for output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobDetailId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, jobDetailId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, status_);
      }
      if (code_ != 0) {
        output.writeUInt32(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, msg_);
      }
      if (progress_ != 0) {
        output.writeUInt32(5, progress_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(output_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, output_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jobDetailId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, jobDetailId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, status_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, msg_);
      }
      if (progress_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, progress_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(output_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, output_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.yx.hoststack.protocol.ws.server.JobResult.TargetResult)) {
        return super.equals(obj);
      }
      org.yx.hoststack.protocol.ws.server.JobResult.TargetResult other = (org.yx.hoststack.protocol.ws.server.JobResult.TargetResult) obj;

      if (!getJobDetailId()
          .equals(other.getJobDetailId())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (getProgress()
          != other.getProgress()) return false;
      if (!getOutput()
          .equals(other.getOutput())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBDETAILID_FIELD_NUMBER;
      hash = (53 * hash) + getJobDetailId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
      hash = (53 * hash) + getProgress();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.yx.hoststack.protocol.ws.server.JobResult.TargetResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.yx.hoststack.protocol.ws.server.TargetResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.yx.hoststack.protocol.ws.server.TargetResult)
        org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.class, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder.class);
      }

      // Construct using org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        jobDetailId_ = "";
        status_ = "";
        code_ = 0;
        msg_ = "";
        progress_ = 0;
        output_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor;
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getDefaultInstanceForType() {
        return org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.getDefaultInstance();
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult build() {
        org.yx.hoststack.protocol.ws.server.JobResult.TargetResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult buildPartial() {
        org.yx.hoststack.protocol.ws.server.JobResult.TargetResult result = new org.yx.hoststack.protocol.ws.server.JobResult.TargetResult(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.yx.hoststack.protocol.ws.server.JobResult.TargetResult result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.jobDetailId_ = jobDetailId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.msg_ = msg_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.progress_ = progress_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.output_ = output_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.yx.hoststack.protocol.ws.server.JobResult.TargetResult) {
          return mergeFrom((org.yx.hoststack.protocol.ws.server.JobResult.TargetResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.yx.hoststack.protocol.ws.server.JobResult.TargetResult other) {
        if (other == org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.getDefaultInstance()) return this;
        if (!other.getJobDetailId().isEmpty()) {
          jobDetailId_ = other.jobDetailId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getProgress() != 0) {
          setProgress(other.getProgress());
        }
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                jobDetailId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                code_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                msg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                progress_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                output_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object jobDetailId_ = "";
      /**
       * <code>string jobDetailId = 1;</code>
       * @return The jobDetailId.
       */
      public java.lang.String getJobDetailId() {
        java.lang.Object ref = jobDetailId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobDetailId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jobDetailId = 1;</code>
       * @return The bytes for jobDetailId.
       */
      public com.google.protobuf.ByteString
          getJobDetailIdBytes() {
        java.lang.Object ref = jobDetailId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jobDetailId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jobDetailId = 1;</code>
       * @param value The jobDetailId to set.
       * @return This builder for chaining.
       */
      public Builder setJobDetailId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jobDetailId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string jobDetailId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobDetailId() {
        jobDetailId_ = getDefaultInstance().getJobDetailId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string jobDetailId = 1;</code>
       * @param value The bytes for jobDetailId to set.
       * @return This builder for chaining.
       */
      public Builder setJobDetailIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jobDetailId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 2;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>uint32 code = 3;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>uint32 code = 3;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {

        code_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 code = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 4;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 4;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        msg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        msg_ = getDefaultInstance().getMsg();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 4;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        msg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <code>uint32 progress = 5;</code>
       * @return The progress.
       */
      @java.lang.Override
      public int getProgress() {
        return progress_;
      }
      /**
       * <code>uint32 progress = 5;</code>
       * @param value The progress to set.
       * @return This builder for chaining.
       */
      public Builder setProgress(int value) {

        progress_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 progress = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        progress_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>string output = 6;</code>
       * @return The output.
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output = 6;</code>
       * @return The bytes for output.
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output = 6;</code>
       * @param value The output to set.
       * @return This builder for chaining.
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        output_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string output = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutput() {
        output_ = getDefaultInstance().getOutput();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string output = 6;</code>
       * @param value The bytes for output to set.
       * @return This builder for chaining.
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        output_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.yx.hoststack.protocol.ws.server.TargetResult)
    }

    // @@protoc_insertion_point(class_scope:org.yx.hoststack.protocol.ws.server.TargetResult)
    private static final org.yx.hoststack.protocol.ws.server.JobResult.TargetResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.yx.hoststack.protocol.ws.server.JobResult.TargetResult();
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TargetResult>
        PARSER = new com.google.protobuf.AbstractParser<TargetResult>() {
      @java.lang.Override
      public TargetResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TargetResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TargetResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JobTargetResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.yx.hoststack.protocol.ws.server.JobTargetResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> 
        getTargetResultList();
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getTargetResult(int index);
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    int getTargetResultCount();
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    java.util.List<? extends org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder> 
        getTargetResultOrBuilderList();
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder getTargetResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.yx.hoststack.protocol.ws.server.JobTargetResult}
   */
  public static final class JobTargetResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.yx.hoststack.protocol.ws.server.JobTargetResult)
      JobTargetResultOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        JobTargetResult.class.getName());
    }
    // Use JobTargetResult.newBuilder() to construct.
    private JobTargetResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private JobTargetResult() {
      targetResult_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.class, org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.Builder.class);
    }

    public static final int TARGETRESULT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> targetResult_;
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> getTargetResultList() {
      return targetResult_;
    }
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder> 
        getTargetResultOrBuilderList() {
      return targetResult_;
    }
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    @java.lang.Override
    public int getTargetResultCount() {
      return targetResult_.size();
    }
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    @java.lang.Override
    public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getTargetResult(int index) {
      return targetResult_.get(index);
    }
    /**
     * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
     */
    @java.lang.Override
    public org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder getTargetResultOrBuilder(
        int index) {
      return targetResult_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < targetResult_.size(); i++) {
        output.writeMessage(1, targetResult_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < targetResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, targetResult_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult)) {
        return super.equals(obj);
      }
      org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult other = (org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult) obj;

      if (!getTargetResultList()
          .equals(other.getTargetResultList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTargetResultCount() > 0) {
        hash = (37 * hash) + TARGETRESULT_FIELD_NUMBER;
        hash = (53 * hash) + getTargetResultList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.yx.hoststack.protocol.ws.server.JobTargetResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.yx.hoststack.protocol.ws.server.JobTargetResult)
        org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.class, org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.Builder.class);
      }

      // Construct using org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (targetResultBuilder_ == null) {
          targetResult_ = java.util.Collections.emptyList();
        } else {
          targetResult_ = null;
          targetResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.yx.hoststack.protocol.ws.server.JobResult.internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor;
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult getDefaultInstanceForType() {
        return org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.getDefaultInstance();
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult build() {
        org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult buildPartial() {
        org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult result = new org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult result) {
        if (targetResultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            targetResult_ = java.util.Collections.unmodifiableList(targetResult_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.targetResult_ = targetResult_;
        } else {
          result.targetResult_ = targetResultBuilder_.build();
        }
      }

      private void buildPartial0(org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult) {
          return mergeFrom((org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult other) {
        if (other == org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult.getDefaultInstance()) return this;
        if (targetResultBuilder_ == null) {
          if (!other.targetResult_.isEmpty()) {
            if (targetResult_.isEmpty()) {
              targetResult_ = other.targetResult_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTargetResultIsMutable();
              targetResult_.addAll(other.targetResult_);
            }
            onChanged();
          }
        } else {
          if (!other.targetResult_.isEmpty()) {
            if (targetResultBuilder_.isEmpty()) {
              targetResultBuilder_.dispose();
              targetResultBuilder_ = null;
              targetResult_ = other.targetResult_;
              bitField0_ = (bitField0_ & ~0x00000001);
              targetResultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTargetResultFieldBuilder() : null;
            } else {
              targetResultBuilder_.addAllMessages(other.targetResult_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.yx.hoststack.protocol.ws.server.JobResult.TargetResult m =
                    input.readMessage(
                        org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.parser(),
                        extensionRegistry);
                if (targetResultBuilder_ == null) {
                  ensureTargetResultIsMutable();
                  targetResult_.add(m);
                } else {
                  targetResultBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> targetResult_ =
        java.util.Collections.emptyList();
      private void ensureTargetResultIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          targetResult_ = new java.util.ArrayList<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult>(targetResult_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.yx.hoststack.protocol.ws.server.JobResult.TargetResult, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder, org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder> targetResultBuilder_;

      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> getTargetResultList() {
        if (targetResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(targetResult_);
        } else {
          return targetResultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public int getTargetResultCount() {
        if (targetResultBuilder_ == null) {
          return targetResult_.size();
        } else {
          return targetResultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult getTargetResult(int index) {
        if (targetResultBuilder_ == null) {
          return targetResult_.get(index);
        } else {
          return targetResultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder setTargetResult(
          int index, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult value) {
        if (targetResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetResultIsMutable();
          targetResult_.set(index, value);
          onChanged();
        } else {
          targetResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder setTargetResult(
          int index, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder builderForValue) {
        if (targetResultBuilder_ == null) {
          ensureTargetResultIsMutable();
          targetResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          targetResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder addTargetResult(org.yx.hoststack.protocol.ws.server.JobResult.TargetResult value) {
        if (targetResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetResultIsMutable();
          targetResult_.add(value);
          onChanged();
        } else {
          targetResultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder addTargetResult(
          int index, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult value) {
        if (targetResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTargetResultIsMutable();
          targetResult_.add(index, value);
          onChanged();
        } else {
          targetResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder addTargetResult(
          org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder builderForValue) {
        if (targetResultBuilder_ == null) {
          ensureTargetResultIsMutable();
          targetResult_.add(builderForValue.build());
          onChanged();
        } else {
          targetResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder addTargetResult(
          int index, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder builderForValue) {
        if (targetResultBuilder_ == null) {
          ensureTargetResultIsMutable();
          targetResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          targetResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder addAllTargetResult(
          java.lang.Iterable<? extends org.yx.hoststack.protocol.ws.server.JobResult.TargetResult> values) {
        if (targetResultBuilder_ == null) {
          ensureTargetResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, targetResult_);
          onChanged();
        } else {
          targetResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder clearTargetResult() {
        if (targetResultBuilder_ == null) {
          targetResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          targetResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public Builder removeTargetResult(int index) {
        if (targetResultBuilder_ == null) {
          ensureTargetResultIsMutable();
          targetResult_.remove(index);
          onChanged();
        } else {
          targetResultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder getTargetResultBuilder(
          int index) {
        return getTargetResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder getTargetResultOrBuilder(
          int index) {
        if (targetResultBuilder_ == null) {
          return targetResult_.get(index);  } else {
          return targetResultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public java.util.List<? extends org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder> 
           getTargetResultOrBuilderList() {
        if (targetResultBuilder_ != null) {
          return targetResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(targetResult_);
        }
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder addTargetResultBuilder() {
        return getTargetResultFieldBuilder().addBuilder(
            org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.getDefaultInstance());
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder addTargetResultBuilder(
          int index) {
        return getTargetResultFieldBuilder().addBuilder(
            index, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.getDefaultInstance());
      }
      /**
       * <code>repeated .org.yx.hoststack.protocol.ws.server.TargetResult targetResult = 1;</code>
       */
      public java.util.List<org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder> 
           getTargetResultBuilderList() {
        return getTargetResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.yx.hoststack.protocol.ws.server.JobResult.TargetResult, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder, org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder> 
          getTargetResultFieldBuilder() {
        if (targetResultBuilder_ == null) {
          targetResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.yx.hoststack.protocol.ws.server.JobResult.TargetResult, org.yx.hoststack.protocol.ws.server.JobResult.TargetResult.Builder, org.yx.hoststack.protocol.ws.server.JobResult.TargetResultOrBuilder>(
                  targetResult_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          targetResult_ = null;
        }
        return targetResultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.yx.hoststack.protocol.ws.server.JobTargetResult)
    }

    // @@protoc_insertion_point(class_scope:org.yx.hoststack.protocol.ws.server.JobTargetResult)
    private static final org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult();
    }

    public static org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JobTargetResult>
        PARSER = new com.google.protobuf.AbstractParser<JobTargetResult>() {
      @java.lang.Override
      public JobTargetResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<JobTargetResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JobTargetResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.yx.hoststack.protocol.ws.server.JobResult.JobTargetResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017JobResult.proto\022#org.yx.hoststack.prot" +
      "ocol.ws.server\"p\n\014TargetResult\022\023\n\013jobDet" +
      "ailId\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\014\n\004code\030\003 \001(" +
      "\r\022\013\n\003msg\030\004 \001(\t\022\020\n\010progress\030\005 \001(\r\022\016\n\006outp" +
      "ut\030\006 \001(\t\"Z\n\017JobTargetResult\022G\n\014targetRes" +
      "ult\030\001 \003(\01321.org.yx.hoststack.protocol.ws" +
      ".server.TargetResultb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_yx_hoststack_protocol_ws_server_TargetResult_descriptor,
        new java.lang.String[] { "JobDetailId", "Status", "Code", "Msg", "Progress", "Output", });
    internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_yx_hoststack_protocol_ws_server_JobTargetResult_descriptor,
        new java.lang.String[] { "TargetResult", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
