LogPath: ${LogDir:logs}
app-version: @project.version@

server:
  port: 8800
  servlet:
    context-path: /hs-core
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 20480 # 20KB
  shutdown: graceful

spring:
  main:
    # Since virtual threads are daemon threads, if all JVM threads are virtual threads, the JVM will exit directly. Therefore, the official recommendation is to enable the following properties to prevent the main thread from exiting the JVM
    keep-alive: true
  cloud:
    config:
      allow-override: true
      override-none: true
    nacos:
      config:
        import-check:
          enabled: false
  application:
    name: center
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.51.231:6446/host_stack_center?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: Root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.51.231:6446/host_stack_center?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: Root
#  data:
#    redis:
#      host: 192.168.51.233
#      port: 7006
#      connect-timeout: 5s
#      client-name: host_stack_cli
#      client-type: lettuce
#      database: 0
#      lettuce:
#        pool:
#          max-active: 100
#          max-wait: -1
#          max-idle: 50
#          min-idle: 50
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/**/*.xml,classpath*:mappers/*.xml
  global-config:
    # Close the mybatis plus startup icon
    banner: false

#okhttp:
#  enable: true
#  # [OPS-MODIFY] Socket connection timeout (seconds)
#  connect-timeout: 5
#  # [OPS-MODIFY] Socket read timeout (seconds)
#  read-timeout: 15
#  # [OPS-MODIFY] Socket write timeout (seconds)
#  write-timeout: 5
#  # [OPS-MODIFY] Maximum number of idle connections
#  max-idle-connections: 10
#  # [OPS-MODIFY] Maximum survival time of idle connections (seconds)
#  keep-alive-duration: 3
#  # [OPS-MODIFY] retry when the connection failure
#  retry-on-connection-failure: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: DEBUG
      mybatis:
        plus: DEBUG
    com:
      alibaba:
        druid: DEBUG
    root: debug
    org.yx.lib.utils.logger.KvLogger: debug

